export const images = {
  appleAuthLogo: require("@/assets/images/apple-auth-logo.png"),
  earth: require("@/assets/images/earth.png"),
  flagChinese: require("@/assets/images/flags/flag-chinese.png"),
  flagFrench: require("@/assets/images/flags/flag-french.png"),
  flagGerman: require("@/assets/images/flags/flag-german.png"),
  flagJapanese: require("@/assets/images/flags/flag-japanese.png"),
  flagKorean: require("@/assets/images/flags/flag-korean.png"),
  flagSpanish: require("@/assets/images/flags/flag-spanish.png"),
  googleAuthLogo: require("@/assets/images/google-auth-logo.png"),
  languageWorld: require("@/assets/images/language-world-full.png"),
  mascotAuth: require("@/assets/images/mascot-auth.png"),
  mascotLogo: require("@/assets/images/moscot-logo.png"),
  mascotWelcome: require("@/assets/images/mascot-welcome.png"),
  palace: require("@/assets/images/palace.png"),
  seeAllLanguagesButton: require("@/assets/images/see-all-languages-button.png"),
  streakFire: require("@/assets/images/streak-fire.png"),
  tabAiTeacherActive: require("@/assets/images/tabIcons/ref-tab-ai-teacher-active.png"),
  tabAiTeacher: require("@/assets/images/tabIcons/ref-tab-ai-teacher.png"),
  tabChatActive: require("@/assets/images/tabIcons/ref-tab-chat-active.png"),
  tabChat: require("@/assets/images/tabIcons/ref-tab-chat.png"),
  tabHomeActive: require("@/assets/images/tabIcons/ref-tab-home-active.png"),
  tabHome: require("@/assets/images/tabIcons/ref-tab-home.png"),
  tabLearnActive: require("@/assets/images/tabIcons/ref-tab-learn-active.png"),
  tabLearn: require("@/assets/images/tabIcons/ref-tab-learn.png"),
  tabProfileActive: require("@/assets/images/tabIcons/ref-tab-profile-active.png"),
  tabProfile: require("@/assets/images/tabIcons/ref-tab-profile.png"),
  teacherPortrait: {
    uri: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=240&h=240&fit=crop&crop=faces",
  },
  treasure: require("@/assets/images/treasure.png"),
};
