export const typeScale = [
  {
    label: "H1",
    role: "Page / Screen Title",
    size: "32px",
    weight: "Bold",
    lineHeight: "1.2",
    previewClassName: "text-h1 font-poppins-bold text-text-primary",
  },
  {
    label: "H2",
    role: "Section Title",
    size: "24px",
    weight: "SemiBold",
    lineHeight: "1.3",
    previewClassName: "text-h2 font-poppins-semibold text-text-primary",
  },
  {
    label: "H3",
    role: "Card / Module Title",
    size: "20px",
    weight: "SemiBold",
    lineHeight: "1.3",
    previewClassName: "text-h3 font-poppins-semibold text-text-primary",
  },
  {
    label: "H4",
    role: "Subheading",
    size: "16px",
    weight: "Medium",
    lineHeight: "1.4",
    previewClassName: "text-h4 font-poppins-medium text-text-primary",
  },
  {
    label: "Body Large",
    role: "Important content",
    size: "16px",
    weight: "Regular",
    lineHeight: "1.6",
    previewClassName: "text-body-lg font-poppins-regular text-text-primary",
  },
  {
    label: "Body Medium",
    role: "Body text",
    size: "14px",
    weight: "Regular",
    lineHeight: "1.6",
    previewClassName: "text-body-md font-poppins-regular text-text-primary",
  },
  {
    label: "Body Small",
    role: "Supporting text",
    size: "13px",
    weight: "Regular",
    lineHeight: "1.6",
    previewClassName: "text-body-sm font-poppins-regular text-text-primary",
  },
  {
    label: "Caption",
    role: "Labels, meta text",
    size: "11px",
    weight: "Regular",
    lineHeight: "1.4",
    previewClassName: "text-caption font-poppins-regular text-text-primary",
  },
] as const;
